In [1]:
from MAUtil import *
from MAInit import *

In [2]:
#############################################################################3
# name = 'Au_111_u2'
# name = 'Au_100_u2'
# name = 'Pd_111_u2'
# name = 'Pd_100_u2'
# name = 'Al_111_u2'
# name = 'Al_100_u2'
# name = 'Ni_111_u2'
name = 'Ni_100_u2'

inname = name + '.traj'
atoms = init_query(inname, 'spacom')
bareatoms, poslis = removemolecule(atoms, ['C', 'O'])

In [3]:
barestruct = AseAtomsAdaptor.get_structure(bareatoms)
baresites = getadsites(bareatoms, False)
d = 1.148

maxmole = 4
mindist = 2.5 # must be not 0
molecule = Atoms('CO', positions=[(0., 0., 0.), (0., 0., d)], cell=(10., 10., 10.))

In [4]:
sites0_ = baresites['all']
sites0 = [list(i) for i in sites0_]

group = creategroup(bareatoms, sites0)

rused = []
for i in reversed(range(len(sites0))):
    for j in range(len(poslis)):
        if np.allclose(sites0[i][:2], poslis[j][:2]):
            tmp = sites0.pop(i)
            rused.append(tmp)
baresites, rused

Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!


({'ontop': [array([ 0.        ,  0.        , 17.31812996]),
   array([ 2.50699051,  0.        , 17.31812996]),
   array([ 0.        ,  2.50699051, 17.31812996]),
   array([ 2.50699051,  2.50699051, 17.31812996])],
  'bridge': [array([ 0.        ,  3.76048576, 17.31812996]),
   array([ 1.25349525,  2.50699051, 17.31812996]),
   array([ 1.25349525,  3.76048576, 17.31812996]),
   array([ 2.50699051,  3.76048576, 17.31812996]),
   array([ 3.76048576,  3.76048576, 17.31812996]),
   array([ 3.76048576,  2.50699051, 17.31812996]),
   array([ 3.76048576,  0.        , 17.31812996]),
   array([ 1.25349525,  0.        , 17.31812996]),
   array([ 3.76048576,  1.25349525, 17.31812996]),
   array([ 2.50699051,  1.25349525, 17.31812996]),
   array([2.22665487e-15, 1.25349525e+00, 1.73181300e+01]),
   array([ 1.25349525,  1.25349525, 17.31812996])],
  'hollow': [],
  'all': [array([ 0.        ,  0.        , 17.31812996]),
   array([ 2.50699051,  0.        , 17.31812996]),
   array([ 0.        ,  2.506

In [5]:
group

[[[0.0, 0.0, 17.3181299622],
  [2.5069905063353186, 0.0, 17.3181299622],
  [0.0, 2.5069905063353186, 17.3181299622],
  [2.5069905063353186, 2.5069905063353186, 17.3181299622]],
 [[0.0, 1.2534952531676593, 17.3181299622],
  [1.2534952531676593, 0.0, 17.3181299622],
  [2.5069905063353186, 1.2534952531676593, 17.3181299622],
  [1.2534952531676593, 2.5069905063353186, 17.3181299622],
  [3.760485759502978, 2.5069905063353186, 17.3181299622],
  [3.760485759502978, 0.0, 17.3181299622],
  [2.5069905063353186, 3.760485759502978, 17.3181299622],
  [0.0, 3.760485759502978, 17.3181299622]],
 [[1.2534952531676593, 1.2534952531676593, 17.3181299622],
  [3.760485759502978, 1.2534952531676593, 17.3181299622],
  [1.2534952531676593, 3.760485759502978, 17.3181299622],
  [3.760485759502978, 3.76048575950298, 17.3181299622]]]

In [6]:
allatoms, allused, mindistlis, numdict, molenum \
    = getuniqueatoms(atoms, bareatoms, sites0, maxmole, mindist, rused, group, molecule)

Used initialized!
1-------Ni16CO-------
2-------Ni16COCO-------
3-------Ni16COCOCO-------
4-------Ni16COCOCOCO-------
Distance 1.25 is below 2.5
Distance 1.77 is below 2.5
Distance 1.25 is below 2.5
Distance 1.25 is below 2.5
Distance 1.25 is below 2.5
Distance 1.77 is below 2.5
3-------Ni16COCOCO-------
Distance 1.25 is below 2.5
Distance 1.25 is below 2.5
Distance 1.25 is below 2.5
Distance 1.25 is below 2.5
4-------Ni16COCOCOCO-------
Distance 1.77 is below 2.5
Distance 1.25 is below 2.5
2-------Ni16COCO-------
Symmetrically same structure found!
Distance 1.25 is below 2.5
Distance 1.77 is below 2.5
Distance 1.25 is below 2.5
Distance 1.77 is below 2.5
2-------Ni16COCO-------
Distance 1.25 is below 2.5
Symmetrically same structure found!
Distance 1.25 is below 2.5
Distance 1.25 is below 2.5
Distance 1.25 is below 2.5
Distance 1.25 is below 2.5
Distance 1.77 is below 2.5
3-------Ni16COCOCO-------
Distance 1.25 is below 2.5
Symmetrically same structure found!
Distance 1.25 is below 2.

In [7]:
print(len(allatoms))

for num in numdict:
    print(num, numdict[num])

24
1 3
2 9
3 7
4 5


In [8]:
mindistlis

[5.013981012670637,
 2.5069905063353186,
 2.5069905063353186,
 2.5069905063353186,
 2.5069905063353186,
 2.5069905063353177,
 3.5454199748,
 2.8029005955561948,
 2.5069905063353177,
 5.013981012670637,
 2.5069905063353186,
 2.5069905063353177,
 2.5069905063353177,
 2.5069905063353186,
 2.5069905063353177,
 3.5454199747999997,
 2.802900595556194,
 2.5069905063353177,
 2.5069905063353177,
 5.013981012670637,
 2.5069905063353177,
 2.5069905063353177,
 2.5069905063353164,
 3.545419974799998]

In [9]:
count = 0
indexlist = []
for i in range(len(mindistlis)):
    if mindistlis[i] > 2.5:
        indexlist.append(i)
        count += 1
# count, indexlist

In [10]:
# for i in range(len(allatoms)): # len(allatoms)
# #     if 'COCOCOCOCO' in str(allatoms[i].symbols):
#     view(allatoms[i])
#     print(allatoms[i].symbols)
# #         print('a')

In [11]:
for i in range(len(allatoms)):
#     if 'COCOCOCOCO' in str(allatoms[i].symbols):
    outname = name + str('_no') + str('{0:03d}'.format(i+1)) +'_CO_n' + str(molenum[i]) + str('_d') + str(int(np.ceil(mindistlis[i]/0.5)-3))  + '.traj'
    print(outname)
    outpath = '/home/katsuyut/init/' + str(outname)
    allatoms[i].write(outpath)

Ni_100_u2_no001_CO_n1_d8.traj
Ni_100_u2_no002_CO_n2_d3.traj
Ni_100_u2_no003_CO_n3_d3.traj
Ni_100_u2_no004_CO_n4_d3.traj
Ni_100_u2_no005_CO_n3_d3.traj
Ni_100_u2_no006_CO_n4_d3.traj
Ni_100_u2_no007_CO_n2_d5.traj
Ni_100_u2_no008_CO_n2_d3.traj
Ni_100_u2_no009_CO_n3_d3.traj
Ni_100_u2_no010_CO_n1_d8.traj
Ni_100_u2_no011_CO_n2_d3.traj
Ni_100_u2_no012_CO_n3_d3.traj
Ni_100_u2_no013_CO_n4_d3.traj
Ni_100_u2_no014_CO_n3_d3.traj
Ni_100_u2_no015_CO_n4_d3.traj
Ni_100_u2_no016_CO_n2_d5.traj
Ni_100_u2_no017_CO_n2_d3.traj
Ni_100_u2_no018_CO_n3_d3.traj
Ni_100_u2_no019_CO_n2_d3.traj
Ni_100_u2_no020_CO_n1_d8.traj
Ni_100_u2_no021_CO_n2_d3.traj
Ni_100_u2_no022_CO_n3_d3.traj
Ni_100_u2_no023_CO_n4_d3.traj
Ni_100_u2_no024_CO_n2_d5.traj
