In [4]:
from MAUtil import *
from MAInit import *

In [38]:
#############################################################################3
# name = 'Au_111_u2'
# name = 'Au_100_u2'
# name = 'Pd_111_u2'
# name = 'Pd_100_u2'
# name = 'Al_111_u2'
# name = 'Al_100_u2'
# name = 'Ni_111_u2'
# name = 'Ni_100_u1'
# name = 'Ru_0001_u2'
name = 'Zn_0001_u2'
# name = 'Rh_111_u2'
# name = 'Rh_100_u2'

inname = name + '.traj'
atoms = init_query(inname, 'spacom')
bareatoms, poslis = removemolecule(atoms, ['C', 'O'])

In [44]:
barestruct = AseAtomsAdaptor.get_structure(bareatoms)
baresites = getadsites(bareatoms, False)
d = 1.148

maxmole = 4
mindist = 0.000001 # must be not 0
molecule = Atoms('CO', positions=[(0., 0., 0.), (0., 0., d)], cell=(10., 10., 10.))

In [45]:
sites0_ = baresites['all']
sites0 = [list(i) for i in sites0_]

group = creategroup(bareatoms, sites0)

rused = []
for i in reversed(range(len(sites0))):
    for j in range(len(poslis)):
        if np.allclose(sites0[i][:2], poslis[j][:2]):
            tmp = sites0.pop(i)
            rused.append(tmp)
baresites, rused

Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!


({'ontop': [array([ 0.        ,  0.        , 19.42502659]),
   array([ 2.7135598 ,  0.        , 19.42502659]),
   array([ 1.3567799 ,  2.35001172, 19.42502659]),
   array([ 4.0703397 ,  2.35001172, 19.42502659])],
  'bridge': [array([ 4.74872965,  1.17500586, 19.42502659]),
   array([ 3.39194975,  1.17500586, 19.42502659]),
   array([ 2.7135598 ,  2.35001172, 19.42502659]),
   array([ 2.03516985,  1.17500586, 19.42502659]),
   array([ 6.10550956,  1.17500586, 19.42502659]),
   array([ 5.42711961,  2.35001172, 19.42502659]),
   array([ 7.46228946,  3.52501759, 19.42502659]),
   array([ 3.39194975,  3.52501759, 19.42502659]),
   array([ 4.74872965,  3.52501759, 19.42502659]),
   array([ 1.3567799 ,  0.        , 19.42502659]),
   array([ 6.10550956,  3.52501759, 19.42502659]),
   array([4.07033970e+00, 2.08722970e-15, 1.94250266e+01])],
  'hollow': [array([ 4.0703397 ,  0.78333724, 19.42502659]),
   array([ 2.7135598 ,  1.56667448, 19.42502659]),
   array([ 5.42711961,  1.56667448, 19.425

In [46]:
group

[[[0.0, 0.0, 19.425026588370002],
  [2.71355980277, 0.0, 19.425026588370002],
  [1.356779901385, 2.3500117238871105, 19.425026588370002],
  [4.070339704155, 2.3500117238871105, 19.425026588370002]],
 [[3.3919497534624976, 1.1750058619435553, 19.425026588370002],
  [4.070339704155, 0.0, 19.425026588370002],
  [4.7487296548475, 1.1750058619435553, 19.425026588370002],
  [0.6783899506925, 1.1750058619435553, 19.425026588370002],
  [1.356779901385, 0.0, 19.425026588370002],
  [2.0351698520775, 1.1750058619435553, 19.425026588370002],
  [2.71355980277, 2.3500117238871105, 19.425026588370002],
  [5.42711960554, 2.3500117238871105, 19.425026588370002],
  [3.3919497534624963, 3.525017585830668, 19.425026588370002],
  [7.462289457617496, 3.525017585830668, 19.425026588370002],
  [4.748729654847494, 3.525017585830666, 19.425026588370002],
  [6.1055095562325, 3.525017585830666, 19.425026588370002]],
 [[4.070339704154996, 0.7833372412957035, 19.425026588370002],
  [1.356779901385, 0.78333724129570

In [47]:
allatoms, allused, mindistlis, numdict, molenum \
    = getuniqueatoms(atoms, bareatoms, sites0, maxmole, mindist, rused, group, molecule)

Used initialized!
1-------Zn16CO-------
2-------Zn16COCO-------
3-------Zn16COCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure f

4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure

Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same str

4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO----

4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!


Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
2-------Zn16COCO-------
Symmetrically same structure found!
Symmetrically same

Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symm

4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetricall

3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Symmetrically same structure found!
Used initialized!
1-------Zn16CO-------
2-------Zn16COCO-------
3-------Zn16COCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
4-------Zn16COCOCOCO-------
3-------Zn16COCOCO-------
Symmetrically same structure found!
Symmetrically same structure found!
4-------

In [43]:
print(len(allatoms))

for num in numdict:
    print(num, numdict[num])

23
1 4
2 10
3 5
4 4


In [37]:
mindistlis

[5.45453792486,
 2.7272689624299993,
 2.727268962429999,
 2.727268962429999,
 3.1491789392229412,
 3.1491789392229412,
 3.1491789392229426,
 5.45453792486,
 2.727268962429999,
 2.7272689624299975,
 2.7272689624299975,
 2.7272689624299993,
 2.838631535244901,
 2.8386315352449025,
 5.454537924859999,
 2.7272689624299975,
 2.7272689624299975,
 2.727268962429993,
 3.1491789392229417,
 5.45453792486,
 2.7272689624299984,
 2.7272689624299984,
 2.7272689624299957]

In [170]:
count = 0
indexlist = []
for i in range(len(mindistlis)):
    if mindistlis[i] > 2.5:
        indexlist.append(i)
        count += 1
# count, indexlist

In [171]:
# for i in range(len(allatoms)): # len(allatoms)
# #     if 'COCOCOCOCO' in str(allatoms[i].symbols):
#     view(allatoms[i])
#     print(allatoms[i].symbols)
# #         print('a')

In [172]:
for i in range(len(allatoms)):
#     if 'COCOCOCOCO' in str(allatoms[i].symbols):
    outname = name + str('_no') + str('{0:03d}'.format(i+1)) +'_CO_n' + str(molenum[i]) + str('_d') + str(int(np.ceil(mindistlis[i]/0.5)-3))  + '.traj'
    print(outname)
    outpath = '/home/katsuyut/init/' + str(outname)
    allatoms[i].write(outpath)

Rh_111_u2_no001_CO_n1_d8.traj
Rh_111_u2_no002_CO_n2_d3.traj
Rh_111_u2_no003_CO_n3_d3.traj
Rh_111_u2_no004_CO_n4_d3.traj
Rh_111_u2_no005_CO_n2_d4.traj
Rh_111_u2_no006_CO_n3_d4.traj
Rh_111_u2_no007_CO_n2_d4.traj
Rh_111_u2_no008_CO_n1_d8.traj
Rh_111_u2_no009_CO_n2_d3.traj
Rh_111_u2_no010_CO_n3_d3.traj
Rh_111_u2_no011_CO_n4_d3.traj
Rh_111_u2_no012_CO_n2_d3.traj
Rh_111_u2_no013_CO_n2_d3.traj
Rh_111_u2_no014_CO_n2_d3.traj
Rh_111_u2_no015_CO_n1_d8.traj
Rh_111_u2_no016_CO_n2_d3.traj
Rh_111_u2_no017_CO_n3_d3.traj
Rh_111_u2_no018_CO_n4_d3.traj
Rh_111_u2_no019_CO_n2_d4.traj
Rh_111_u2_no020_CO_n1_d8.traj
Rh_111_u2_no021_CO_n2_d3.traj
Rh_111_u2_no022_CO_n3_d3.traj
Rh_111_u2_no023_CO_n4_d3.traj
