In [1]:
import numpy as np
import sys, os, random, itertools, warnings, math
import matplotlib.pyplot as plt
from ase import Atoms, Atom
from ase.build import fcc111, fcc100, add_adsorbate, rotate
from ase.calculators.emt import EMT
from ase.calculators.vasp import Vasp, Vasp2
from ase.calculators.singlepoint import SinglePointCalculator as SPC
from ase.constraints import FixAtoms
from ase.eos import EquationOfState
from ase.geometry import find_mic
from ase.io import read, write
from ase.io.trajectory import Trajectory, TrajectoryWriter
from ase.lattice.cubic import FaceCenteredCubic
from ase.optimize import QuasiNewton
from ase.visualize import view
from scipy.spatial.qhull import QhullError
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.analysis.adsorption import AdsorbateSiteFinder

def getadsites(atoms, symm_reduce):
    '''
    Given surface, return sites dictionary.
    '''
    if not symm_reduce:
        struct = AseAtomsAdaptor.get_structure(atoms)
        sites_dict = AdsorbateSiteFinder(struct).find_adsorption_sites(put_inside=True, symm_reduce=0)
        return sites_dict
    
    elif symm_reduce:
        struct = AseAtomsAdaptor.get_structure(atoms)
        sites_dict = AdsorbateSiteFinder(struct).find_adsorption_sites(put_inside=True)
        return sites_dict

In [1]:
import numpy as np
import sys
import copy
import ktms

# env = 'local'
env = 'spacom'
surface = 'Pt'
adsorbate = 'CO'

mirror = '111'
unitlength = 3
molenum = 2 # number of molecules
# mindistlim = 2.5

##################################################################################
### Set coefficients ###
d = 1.13
h = 1.85
layers = 4
# fixlayer = 3
latticeconstant = 4.21027100913
# Cu = 3.67676461295 # previously 3.67674038800827
# Pt = 3.99042863796
# Ag = 4.21027100913

unique = ''

if molenum == 1:
    symred = True
else:
    symred = False

if mirror =='100':
    initatoms = ktms.fcc100(surface, a=latticeconstant, size=(unitlength, unitlength, layers), vacuum=10.0)
elif mirror == '111':
    initatoms = ktms.fcc111(surface, a=latticeconstant, size=(unitlength, unitlength, layers), vacuum=10.0)

### Set molecule ###
name = adsorbate + unique +'.traj'

if ktms.init_query(name, env) != 'No file':
    molecule = ktms.init_query(name, env)
    print(name, 'read')
else:
    molecule = ktms.Atoms(adsorbate, positions=[(0., 0., 0.), (0., 0., d)], cell=(10., 10., 10.))
    trajpath = '/home/katsuyut/init/' + str(name)
#     molecule.write(trajpath)
    print(name, 'created!')


### Set slab ###
name = surface + mirror + '_unit' + str(unitlength) + unique + '.traj'

if ktms.init_query(name, env) != 'No file':
    atoms = ktms.init_query(name, env)
    print(name, 'read')
else:
    atoms = initatoms
    trajpath = '/home/katsuyut/init/' + str(name)
#     atoms.write(trajpath)
    print(name, 'created!')

cell = atoms.cell

# atoms = read('/home/katsuyut/init/' + 'Cu100_unit2.traj')
atoms = read('/home/katsuyut/init/' + 'Cu100_unit2_CO_300_3.traj')
view(atoms)
### Set adsorption sites ###
sites = ktms.getadsites(atoms, True) # all sites
sites

# positions = ktms.getadsitecomb(sites, molenum) # combination of sites with n molecules
# calccombs, uniquecomb, results = ktms.getcalccomb(sites, molenum, cell) # reduced combinations

CO.traj read
Pt111_unit3.traj read


NameError: name 'read' is not defined

In [ ]:
[array([ 0.        ,  0.        , 20.49511058]),
  array([ 0.        ,  2.59984806, 20.49511058]),
  array([ 2.59984806,  2.59984806, 20.49511058])]}

[array([ 0.        ,  0.        , 17.51511058]),
  array([ 0.        ,  1.29992403, 17.51511058]),
  array([ 1.29992403,  1.29992403, 17.51511058])]}